class Critic(object):
    """ A critic takes solution trace generated by the performance system as input and generates training examples along with an estimate of target 
        function value for each training example"""
    def __init__(self, generalizer):
        self._training_examples=[]
        self._target_function_values=[]
        self._generalizer=generalizer

    def append_examples(self,training_example, target_function_value):
        self._training_examples.append(training_example)

        if len(self._target_function_values) > 0 and self._target_function_values[-1] is None:
            weights = self._generalizer.get_weights()

            self._target_function_values[-1] = training_example.calculate_target_value(weights)

        self._target_function_values.append(target_function_value)

    def fetch_training_examples(self):
        return self._training_examples, self._target_function_values